name: Build dist

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  qa:
    uses: ./.github/workflows/qa.yml

  build:
    runs-on: ubuntu-latest

    needs:
      - qa

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build dist
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
